replicaCount: 2
# values.yaml
color: blue


image:
  repository: tanees012/exp-app
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  hosts:
    - host: exp-app.local
      paths:
        - path: /
          pathType: Prefix
          
secret:
  username: admin
  password: securepassword
  
service:
  type: LoadBalancer


resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

