app:
  name: express-app
  image:
    repository: express-app
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    host: expressapp.local
    path: /
    pathType: Prefix

mongodb:
  name: mongo
  image:
    repository: mongo
    tag: latest
  replicaCount: 1
  service:
    port: 27017
  storage:
    size: 1Gi
    accessModes:
      - ReadWriteOnce
  persistence:
    enabled: true

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

