# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp-app-{{ .Values.color }}
  labels:
    app: exp-app
    color: {{ .Values.color }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: exp-app
    meta.helm.sh/release-namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exp-app
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: exp-app
        color: {{ .Values.color }}
    spec:
      containers:
        - name: web
          image: tanees012/exp-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/programmer"
              
              



# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.color }}
  labels:
    app: {{ .Release.Name }}
    color: {{ .Values.color }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        color: {{ .Values.color }}
    spec:
      containers:
      - name: myapp
        image: my-docker-image:latest
        ports:
        - containerPort: 80

